In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
filename = '/content/drive/MyDrive/Coding Dojo Data Science/PandasForDataManipulation/clean_sales_predictions.csv'
df = pd.read_csv(filename)
df.head()

Unnamed: 0 Product ID  ...  Size of Store 2 Size of Store
0           0      FDA15  ...              2.0        Medium
1           1      DRC01  ...              2.0        Medium
2           2      FDN15  ...              2.0        Medium
3           3      FDX07  ...              2.0        Medium
4           4      NCD19  ...              1.0          High

[5 rows x 14 columns]

In [4]:
df.drop(df.columns[[0,1,7,8,9,12]], axis=1, inplace=True)


In [5]:
df.rename(columns={'Size of Store 2': 'Size of Store'}, inplace=True)

In [6]:
df.head()

Weight Low Fat or Regular  ...  Item_Outlet_Sales Size of Store
0    9.30            Low Fat  ...          3735.1380        Medium
1    5.92            Regular  ...           443.4228        Medium
2   17.50            Low Fat  ...          2097.2700        Medium
3   19.20            Regular  ...           732.3800        Medium
4    8.93            Low Fat  ...           994.7052          High

[5 rows x 8 columns]

In [7]:
df['Low Fat or Regular'].unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [8]:
df['Low Fat or Regular']=df['Low Fat or Regular'].replace({'low fat':'Low Fat', 'LF':'Low Fat', 'reg':'Regular'})

In [9]:
df['Low Fat or Regular'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [10]:
df['Grocery Store or Supermarket'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [11]:
df['Grocery Store or Supermarket'].replace({'Supermarket Type1' : 'Supermarket','Supermarket Type2': 'Supermarket','Supermarket Type3': 'Supermarket'},inplace=True)

In [12]:
df['Grocery Store or Supermarket'].unique()

array(['Supermarket', 'Grocery Store'], dtype=object)

In [13]:
df['Product Category'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [14]:
X = df[['Product List Price', 'Product Category','Size of Store']]

In [15]:
y = df[['Item_Outlet_Sales']]


Converting categorical variable into dummy/indicator variables and drop one in each category:

In [16]:
X = pd.get_dummies(data=X, drop_first=True)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 50)

In [18]:
reg = linear_model.LinearRegression()

In [19]:
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
y_predict = reg.predict(X_test)

In [21]:
y_predict

array([[1078.67680614],
       [1046.16360162],
       [ 754.99135892],
       ...,
       [3522.36873454],
       [1886.3367354 ],
       [2468.91722122]])

In [22]:
#R2
score = reg.score(X, y)
print(f"Coefficient of determination R2 is {score.mean()*100:.2f} %")

Coefficient of determination R2 is 33.36 %


In [23]:
reg.intercept_

array([98.64415678])

In [24]:
reg.coef_

array([[  15.58228407,   21.86596794,  -87.49858148,   64.74190333,
         -64.40469226,   -8.08464578,   43.62560736,   -2.07200309,
         -22.7882599 ,  -55.69361823,   -7.73103632, -113.10968625,
         141.65149166,   11.90396851,  -28.24936863,   74.44790386,
        -395.42413014,   -1.44022134]])

In [25]:
#The mean squared error (MSE)
from sklearn.metrics import mean_squared_error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_predict))

Mean squared error: 1910858.72


The model is producing a very high MSE, indicating that the variance or the bias in the estimator is large.